<?php

include 'taxonomy_walker.admin.inc';
include 'taxonomy_walker.variables.inc';
include 'taxonomy_walker.helpers.inc';
include 'taxonomy_walker.form.inc';
include 'taxonomy_walker.content.inc';
include 'taxonomy_walker.block.inc';
include 'taxonomy_walker.api.inc';

function taxonomy_walker_menu() {
  $items['admin/structure/taxonomy-walker'] = array(
    'page callback' => 'taxonomy_walker_admin_page_view',
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_CALLBACK,
    'title' => 'Admin for Taxonomy Walker'
  );

  return $items;
}

function taxonomy_walker_term_view($options = array()) {
  return drupal_get_form('taxonomy_walker_form', $options);  
}
function taxonomy_walker_content_view($options = array()) {
  return drupal_get_form('taxonomy_walker_content_form', $options);  
}
