<?php

include 'taxonomy_walker.admin.inc';
include 'taxonomy_walker.variables.inc';
include 'taxonomy_walker.helpers.inc';
include 'taxonomy_walker.form.inc';
include 'taxonomy_walker.block.inc';

function taxonomy_walker_menu() {
  $items['admin/structure/taxonomy-walker'] = array(
    'page callback' => 'taxonomy_walker_admin_page_view',
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_CALLBACK,
    'title' => 'Admin for Taxonomy Walker'
  );

  $options = array(
    'form_id' => 'support_matrix', 
    'term_id' => 32, 
    'type' => 'button', 
    'include_buttons' => false, 
    'terms_at_a_time' => 0,
    '#attributes' => array('class' => array('taxonomy-walker-with-buttons', 'support-matrix'))
  );

  $items['support'] = array(
    'page callback' => 'taxonomy_walker_multi_page_view',
    'page arguments' => array($options),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Support Matrix'
  );

  $options = array(
    'form_id' => 'product_finder', 
    'term_id' => 15, 
    'type' => 'button', 
    'types' => array('image_button'),
    'include_buttons' => false, 
    'include_restart_button' => true,
    'terms_at_a_time' => 1,
    '#attributes' => array('class' => array('taxonomy-walker-with-image-buttons', 'product-finder'))
  );

  $items['product-finder'] = array(
    'page callback' => 'taxonomy_walker_multi_page_view',
    'page arguments' => array($options),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Who Are You?'
  );


  return $items;
}

function taxonomy_walker_multi_page_view($options = array()) {
  return drupal_get_form('taxonomy_walker_form', $options);  
}